### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by chrishwiggins** [jastrauss/SheetReader#2]
https://github.com/jastrauss/SheetReader/blob/e1aef35a5d9b589052e11a0f6ffb1678a91c1bee/google_sheets_api.py#L25

could you provide an example of what this file looks like? (w/o your secret key natch)

**Comment by jastrauss** [comment]
`.credentials/sheets.googleapis.com-python-quickstart.json ` should get autogenerated. When you try to run a SheetReader for the first time, it should open a browser and ask you to auth ([relevant code](https://github.com/jastrauss/SheetReader/blob/e1aef35a5d9b589052e11a0f6ffb1678a91c1bee/google_sheets_api.py#L53)). Then it will automatically save the OAuth tokens in `.credentials/sheets.googleapis.com-python-quickstart.json`. (It will save in the working directory, not ~. I'll change that comment.)

```
{
    "access_token": "",
    "client_id": "",
    "client_secret": "",
    "refresh_token": "",
    "token_expiry": "",
    "token_uri": "https://accounts.google.com/o/oauth2/token",
    "user_agent": "Google Sheets API Python Quickstart",
    "revoke_uri": "https://accounts.google.com/o/oauth2/revoke",
    "id_token": null,
    "id_token_jwt": null,
    "token_response": {
        "access_token": "",
        "expires_in": 3599,
        "scope": "https://www.googleapis.com/auth/spreadsheets",
        "token_type": "Bearer"
    },
    "scopes": [
        "https://www.googleapis.com/auth/spreadsheets"
    ],
    "token_info_uri": "https://www.googleapis.com/oauth2/v3/tokeninfo",
    "invalid": false,
    "_class": "OAuth2Credentials",
    "_module": "oauth2client.client"
}
```

**Comment by chrishwiggins** [comment]
cool!
